# Database location
spring.datasource.url=jdbc:sqlite:warmup_db.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate dialect for SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Auto-update database schema based on Java entities
spring.jpa.hibernate.ddl-auto=update

# Show SQL in terminal for debugging purposes
spring.jpa.show-sql=true